services:
  db:
    image: postgres:16-bullseye
    env_file:
      - ./app/.env
    volumes:
      - hwpayweb-pg-vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hwpayweb-network
  # frontend:
  #   build: ./frontend
  #   env_file:
  #     - ./frontend/.env
  #   command: bash -c "npm run dev"
  #   # command: bash -c "npm run build && npm run start"
  #   restart: always
  #   volumes:
  #     - ./frontend:/frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - hwpayweb-network
  app:
    build: ./app
    env_file:
      - ./app/.env
    # command: bash -c "python manage.py runserver 0.0.0.0:3001"
    command: bash -c "uwsgi --socket 0.0.0.0:3001 --protocol http --py-autoreload 1 --ini uwsgi.ini"
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8003:3001"
    links:
      - db:db
    networks:
      - hwpayweb-network

networks:
  hwpayweb-network:
    driver: bridge
volumes:
  hwpayweb-pg-vol:
