# Generated by Django 5.1.4 on 2025-01-14 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='phone_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='articles_of_organization',
            field=models.FileField(blank=True, null=True, upload_to='uploads/articles/'),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='uploads/licenses/'),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='statement_of_information',
            field=models.FileField(blank=True, null=True, upload_to='uploads/statements/'),
        ),
    ]
